config/routes.rb
Rails.application.routes.draw do
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'
get 'home/index'
  resources :orders do
 resources :orderitems
end

   devise_for :users do
 resources :orders
 end
  
 
 resources :items
 
  get '/cart' => 'cart#index'
  get '/cart/:id' => 'cart#add'
  get '/home' => 'home#index'
 get '/about' => 'site#about'
 get '/contact' => 'site#contact'
 get '/cart/remove/:id' => 'cart#remove'
  get '/clearCart' => 'cart#clearCart'
  
  
  post '/validate', :controller=>'cart', :action=>'profane'
  post '/validate1', :controller=>'cart', :action=>'calculate'

 get '/Admin' => 'user#admin_login'
 get '/logout' => 'user#logout'

 get '/checkout' => 'cart#createOrder'
root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :orderitems
 belongs_to :user
end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
# Include default devise modules. Others available are:
 # :confirmable, :lockable, :timeoutable and :omniauthable
 devise :database_authenticatable, :registerable,
 :recoverable, :rememberable, :trackable, :validatable
has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
require 'pfc'
require 'Discount'
class CartController < ApplicationController
def calculate
@total=session[:total]
 @input1= params[:search_string]
 g= Discount.new()
 @result=g.calculate(@input1,@total.to_i)
end
 def profane
  @input1= params[:search_string]
 g = GolfProfanityChecker.new()
 @result = g.swapProfanity(@input1)
 end
 def createOrder
 # Step 1: Get the current user
 @user = User.find(current_user.id)

 # Step 2: Create a new order and associate it with the current user
 @order = @user.orders.build(:order_date => DateTime.now)
 @order.save

 # Step 3: For each item in the cart, create a new item on the order!!
 @cart = session[:cart] || {} # Get the content of the Cart
 @cart.each do | id, quantity |
 item = Item.find_by_id(id)
 @orderitem = @order.orderitems.build(:item_id => item.id, :title =>item.title, :description => item.description, :quantity => quantity, :price=> item.price)
 @orderitem.save
 end
 end
 def add
 # get the ID of the product
id = params[:id]
# if the cart has already been created, use the existing cart
# else create a blank cart
if session[:cart] then
cart = session[:cart]
else
session[:cart] = {}
cart = session[:cart]
end
# if the product has alreadd been added to the cart, increment the value
# else set the value to 1
 if cart[id] then
cart[id] = cart[id] + 1
else
cart[id] = 1
end
# redirect to the cart display page
 redirect_to :action => :index
 end
 def clearCart
 #  set the session variable to nil and redirect
 session[:cart] = nil
 redirect_to :action => :index
 end
 def index
# if there is a cart, pass it to the page for display
# else pass an empty value
 if session[:cart] then
@cart = session[:cart]
else
@cart = {}
end
 end
  def change
 cart = session[:cart]
 id = params[:id];
 quantity = params[:quantity].to_i
 if cart and cart[id]
 unless quantity <= 0
 cart[id] = quantity
 else
 cart.delete id
 end
 end
 redirect_to :action => :index
 end
 def checkout
 flash[:notice] = "CHECKOUT IS NOT IMPLEMENTED YET!!!"
 redirect_to :action => :index
 end
 def remove
 id = params[:id]
 cart = session[:cart]
 cart.delete id

 redirect_to :action => :index
 end
 end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
# GET /items
 # GET /items.json
 #before_filter :authenticate_user!
# before_filter :ensure_admin, :only => [:new, :create, :edit, :destroy]
  #before_action :set_item, only: [:show, :edit, :update, :destroy]
   before_filter :authenticate_user!
 before_filter :ensure_admin, :only => [:new, :create, :edit, :destroy]

before_filter :ensure_admin, :except => [:index,:show]
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end
  def ensure_admin
 unless current_user && current_user.admin?
 render :text => "Access Error Message", :status => :unauthorized
 end
end 

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :category, :brand)
    end
end

app/controllers/orderitems_controller.rb
class OrderitemsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @orders = Order.all
    respond_with(@orders)
  end

  def show
    respond_with(@order)
  end

  def new
    @order = Order.new
    respond_with(@order)
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    @order.save
    respond_with(@order)
  end

  def update
    @order.update(order_params)
    respond_with(@order)
  end

  def destroy
    @order.destroy
    respond_with(@order)
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:order_date, :user_id)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
def login
 end
 def admin_login
 session[:login] = 1
 session[:cart] = nil
 flash[:notice] = "Admin Login Successful!!"
 redirect_to :controller => :items
 end
 def logout
 session[:login] = nil
 session[:cart] = nil
 flash[:notice] = "You have successfully logged out!!"
 redirect_to :controller => :items
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cart/calculate.html.erb
<h3>Your orders has been placed and the notification has been sent to your email.</h3>
<h2>Your total price is <%= @result%></h2>

app/views/cart/createOrder.html.erb
<h3>Your orders has been placed and the notification has been sent to your email.</h3>

app/views/cart/index.html.erb
<h1>Your Cart</h1>
<% if @cart.empty? %>
 <p>Your Cart is empty.</p>
<% end %>
<% total = 0 %>
<table class="cart">
 <tr>
 <td class="legend"></td>
 <td class="legend">Item</td>
 <td class="legend">Price</td>
 <td class="legend">Qty</td>
 <td class="legend">Total</td>
 </tr>
<% @cart.each do | id, quantity | %>
 <% item = Item.find_by_id(id) %>
 <tr>
 <td>
 <div class="image">
 <%= link_to (image_tag item.image_url, :style => "height:40px"), item %>
 </div>
 </td>
 <td class="title"><%= link_to item.title, item %></td>
 <td class="price"><%= number_to_currency(item.price) %></td>
 <td class="quantity"><%= quantity %><br /></td>
 <td class="price">
 <%= number_to_currency(quantity * item.price, :unit => "£") %>
 </td>
 <td><a href="/cart/remove/<%= item.id %>">Remove from Cart</a></td>
 </tr>
 <% total += quantity * item.price %>
<% end %>
 <tr>
 <td colspan="4">
 <div class="total">Total:</div>
 </td>
 <td>
 <div class="price"><%= number_to_currency(total, :unit => "€") %></div>
 </td>
 </tr>
</table>
<br>
<h2>Enter a voucher no. </h2>
<%= form_tag "/validate1" do %>
<%= text_field_tag :search_string %>
<% session[:total]=total %>
<%= submit_tag "Get Discount" %>
<% end %>
<p>
 <%= link_to 'Continue Shopping', :controller => :items %>
  <%= link_to 'Clear Cart', :controller => "cart", :action => "clearCart" %>
 <%= link_to 'Check Out', :controller => "cart", :action => "createOrder" %>
</p>

app/views/cart/profane.html.erb
<h1>Home</h1>

<img src="assets/xmasshop.jpg" height="300" width="650"/>
<h3>THE 2015 TOP BRAND CRICKET BATS AND EQUIPMENT HAVE ARRIVED IN ED SPORTS CRICKET SPECIALIST SHOP - BUY IN-STORE OR ONLINE</h3>
<br>
<br>
<br>
<h1>Check that you are a cricket lover</h1>
<br>
<%= form_tag "/validate" do %>
<%= text_field_tag :search_string %>
<%= submit_tag "Play" %>
<% end %>
<br>
<br>
<strong>The profaned string is <%= @result %></strong>

app/views/home/index.html.erb
<h1>Home</h1>

<img src="assets/xmasshop.jpg" height="300" width="650"/>
<h3>THE 2015 TOP BRAND CRICKET BATS AND EQUIPMENT HAVE ARRIVED IN ED SPORTS CRICKET SPECIALIST SHOP - BUY IN-STORE OR ONLINE</h3>
<br>
<br>
<br>
<h1>Check that you are a cricket lover</h1>
<br>
<%= form_tag "/validate" do %>
<%= text_field_tag :search_string %>
<%= submit_tag "Play" %>
<% end %>
<br>
<br>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Catalog</h1>
<br>
<table class="catalog">
<% @items.each do |item| %>
 <tr>
 <td>
 <div class="image">
 <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
 </div>
 </td>
 <td>
 <div class="title">
 <%= link_to item.title, item %>
 </div>
 <div class="description">
 <%=h item.description %>
 </div>
 <div class="price">
 <%= number_to_currency(item.price, :unit => "&pound;") %>
 </div>
 <div class="links">
<% if user_signed_in? %>
 <a href="/cart/<%= item.id %>">Add to Cart</a><br><br>
 <% end %>

 </div>
 </td>
 <% if current_user.admin? %>
 <td><%= link_to 'Show', item %></td>
 <td><%= link_to 'Edit', edit_item_path(item) %></td>
 <td><%= link_to 'Destroy', item, confirm: 'Are you sure?', method: :delete %></td>
<% end %>
 </tr>
<% end %>
</table>

<% if current_user.admin? %>
 <%= link_to 'New Item', new_item_path %>
<% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @item.image_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Cricketstore</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
 <div id='header'>
 <!-- Header Image Displayes here -->
 </div>
 <div id='menu'>
<div id="navbar">
<ul>
<li><a href="/home">Home</a></li>
<li><a href="/items">Products</a></li>
<li><a href="/about">About</a></li>
<li><a href="/contact">Contact Us</a></li>
<li><%= link_to 'Login', new_user_session_path %></li>
<li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
</ul>
</div>
 </div>
 <div id='container'>
 <div id='content'>
 <p class="notice"><%= flash[:notice] %></p>
 <%= yield %>
 <% if user_signed_in? %>
 <div>Signed in as... <%= current_user.email %> (<%= link_to 'Sign out', destroy_user_session_path, :method => :delete
%>)</div>
<% else %>
 <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
<% end %>
</div>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
 <div id='first-column'>
 <div class="loginbox">
 <h2 class="BoxHeaders"><%= link_to 'Login Here..', new_user_session_path %></h2>
</div>

 <div class="searchbox">
 <% if user_signed_in? %>
<h2 class="BoxHeaders"><a href='/cart'>Cart</a></h2>
<% else %>
<h2 class="BoxHeaders"><a href='#'>Cart</a></h2>
<% end %>
</div>
 </div>
 </div>
 <div id='footer'>
 <h6 class="footertext">&copy; Online Cricket Store &trade; 2013</h6>
 </div>
</body>
</html>

app/views/orderitems/edit.html.erb
<h1>Orderitems#edit</h1>
<p>Find me in app/views/orderitems/edit.html.erb</p>

app/views/orderitems/index.html.erb
<h1>Orderitems#index</h1>
<p>Find me in app/views/orderitems/index.html.erb</p>

app/views/orderitems/new.html.erb
<h1>Orderitems#new</h1>
<p>Find me in app/views/orderitems/new.html.erb</p>

app/views/orderitems/show.html.erb
<h1>Orderitems#show</h1>
<p>Find me in app/views/orderitems/show.html.erb</p>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.datetime_select :order_date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Order date</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_date %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order date:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/site/about.html.erb
<h1>Site#about</h1>
<p>Find me in app/views/site/about.html.erb</p>

app/views/site/contact.html.erb
<h1>Shahnawaz Alam</h1>

<p>Hii,friends.You can buy all the cricket stuff here simply in few clicks.</p>